### ISSUE TITLE
Undeclared Import Files

### ISSUE THREAD

**Issue by Zlarex** [DrOreo002/ENetJavaWrapper#2]
Can you tell me what does import Lombok.Getter used for? Its throw error since there is no such files/classes for Lombok.Getter i think

P.s: ENetJava files

**Comment by DrOreo002** [comment]
Hey sorry for the late response. Github doesn't have any notifications and I didn't watch this repo so yea xD

It's a library for automatic Getter and Setting, you can define it as a library on the pom.xml
